auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 0
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  compactor:
    working_directory: /loki/compactor
    compaction_interval: 5m
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks
limits_config:
  retention_period: 744h # 31 days
  max_label_names_per_series: 30
  max_cache_freshness_per_query: 10m
chunk_store_config:
  max_look_back_period: 744h
ruler:
  alertmanager_url: ''
